# Generated by Django 4.2.7 on 2023-11-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_c2bpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesarequest',
            name='paid',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=255),
        ),
    ]
