# Generated by Django 4.2.7 on 2023-11-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_authtoken_b2crequest_b2cresponse_c2brequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinecheckout',
            name='checkout_request_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='onlinecheckout',
            name='customer_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlinecheckout',
            name='merchant_request_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlinecheckout',
            name='response_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlinecheckout',
            name='transaction_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
