# Generated by Django 4.2.7 on 2023-11-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paybillnumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybillnumbers',
            name='paybill',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
