# Generated by Django 4.2.7 on 2023-11-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_paybillnumbers_paybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecheckout',
            name='call_back_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
