# Generated by Django 4.2.7 on 2024-06-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_onlinecheckout_error_code_onlinecheckout_error_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybillnumbers',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
