# Generated by Django 4.2.7 on 2024-06-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_paybillnumbers_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesarequest',
            name='callback_sent',
            field=models.BooleanField(default=False),
        ),
    ]
