# Generated by Django 4.2.7 on 2025-03-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_c2bpaymentsvalidation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsvalidation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsvalidation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
