# Generated by Django 4.2.7 on 2025-03-14 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_c2bpaymentsconfirmation_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company_code', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='c2bpaymentsconfirmation',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='aims_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='cellulant_flag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='column2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='confirmation_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='fa_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='fetch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='group_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='igas_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='imarika_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='integration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='intergration_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='is_from_reconcilliation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='is_valid_trans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='kavaflag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='kavaresult',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='lob_policyNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='newappflag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='p_aims',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='p_flag',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='p_kava',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='p_kava_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='pollkava',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='recon_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='sirius_error_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='sirius_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='c2bpaymentsconfirmation',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.company'),
        ),
    ]
