# Generated by Django 4.2.7 on 2025-04-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBusinessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
