# Generated by Django 4.2.7 on 2025-04-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_userrequestsmodel_mpesarequest_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesarequest',
            name='lob_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mpesarequest',
            name='update_lob',
            field=models.BooleanField(default=False),
        ),
    ]
