# Generated by Django 4.2.7 on 2025-04-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_mpesarequest_lob_message_mpesarequest_update_lob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c2bpaymentsconfirmation',
            name='MSISDN',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='c2bpaymentsvalidation',
            name='MSISDN',
            field=models.TextField(blank=True, null=True),
        ),
    ]
