# Generated by Django 4.2.7 on 2025-04-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_cardpaymentstransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callbackhanldlers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paybill', models.CharField(max_length=255)),
                ('regex', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='c2bpaymentsvalidation',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='C2BCallbackResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent', models.BooleanField(default=False)),
                ('response', models.TextField()),
                ('callbackhandler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.callbackhanldlers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
