From python:3.8
RUN mkdir -p /usr/src/britam/aims_portal/app
WORKDIR /usr/src/britam/aims_portal/app
COPY . /usr/src/britam/aims_portal/app
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
CMD ["/bin/bash", "./run-uat.sh"]