version: '2'
services:
  britam_payment:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: acruksaksbritam3753.azurecr.io/britam_payment_module:1.3
    volumes:
      - ./:/usr/src/britam/payments/app
    ports:
      - 8077:8077

  


