version: '2'
services:
  britam_payment:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: acruksaksbritam3753.azurecr.io/britam_payment_module:2.9
    volumes:
      - ./:/usr/src/britam/payments/app
    ports:
      - 8077:8077

  # britam_payment_uat:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.uat
  #   image: acruksaksbritam3753.azurecr.io/britam_payment_module_uat:2.7
  #   volumes:
  #     - ./:/usr/src/britam/payments/app/uat
  #   ports:
  #     - 8075:8075


  



